# Generated by Django 2.1 on 2019-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('scity', models.CharField(max_length=30)),
                ('sid', models.IntegerField()),
            ],
        ),
    ]
